
name: container-deployment
trigger: none

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: AzureCLI@2
  displayName: 'Create Storage Account'
  inputs:
    azureSubscription: 'Pay-As-You-Go(df454dbc-c3b7-41b6-b9dc-90d90bf156f9)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
    az storage account create \
    --name actest \
    --resource-group azure-dev-ops-test \
    --sku Standard_RAGRS \
    --kind StorageV2


- task: AzureCLI@2
  displayName: 'Create Blob Container'
  inputs:
    azureSubscription: 'Pay-As-You-Go(df454dbc-c3b7-41b6-b9dc-90d90bf156f9)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az storage container create \
      -n test$(System.JobId) \
      --fail-on-exist \
      --account-name actest