
name: container-deployment
trigger: none

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'


- task: AzureCLI@2
  inputs:
    azureSubscription: 'Pay-As-You-Go(df454dbc-c3b7-41b6-b9dc-90d90bf156f9)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az storage container create \
            -n test$(Build.BuildNumber) \
            --fail-on-exist \
            --account-name azureblobtescm