on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Set shared variables
      run: |
        echo "SHA_IMAGE_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: Check shared variables
      run: |
        echo ${{ env.SHA_IMAGE_TAG }}

      # - name: Build and push
      #   uses: docker/build-push-action@v4
      #   with:
      #     push: true
      #     tags: user/app:${{ env.SHA_IMAGE_TAG }}

    - name: Azure login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az storage blob upload-batch --account-name azureblobtescm  --auth-mode key -d '$web' -s .
    - name: Purge CDN endpoint
      uses: azure/CLI@v1
      with:
        inlineScript: |
           az cdn endpoint purge --content-paths  "/*" \
           --profile-name "cdn-matcham" \
           --name "cdn-matcham-endpoint-bdfqgca0azhud6bb.z01.azurefd.net" \
           --resource-group "azure-dev-ops-test"

    # - name: Deploy to Blob Storage
    #   uses: Azure/blob-upload-action@v1
    #   with:
    #     storageAccountName: '<your-storage-account-name>'
    #     containerName: '<your-container-name>'
    #     sourcePath: '<your-source-path>'
    #     destinationPath: '<your-destination-path>'
