on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    # - name: Checkout code
    #   uses: actions/checkout@v2

    # - name: Set up QEMU
    #   uses: docker/setup-qemu-action@v2

    # - name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v2
    
    # - name: Set shared variables
    #   run: |
    #     echo "SHA_IMAGE_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    # - name: Check shared variables
    #   run: |
    #     echo ${{ env.SHA_IMAGE_TAG }}

      # - name: Build and push
      #   uses: docker/build-push-action@v4
      #   with:
      #     push: true
      #     tags: user/app:${{ env.SHA_IMAGE_TAG }}

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - run: |
        az webapp list --query "[?state=='Running']"

    # - name: Upload to blob storage
    #   run: |
    #       az storage container create \
    #       -n cjmtestcontainer \
    #       --fail-on-exist \
    #       --account-name azureblobtescm


    # - name: Deploy to Blob Storage
    #   uses: Azure/blob-upload-action@v1
    #   with:
    #     storageAccountName: '<your-storage-account-name>'
    #     containerName: '<your-container-name>'
    #     sourcePath: '<your-source-path>'
    #     destinationPath: '<your-destination-path>'
