name: container-deployment
on:
  workflow_dispatch:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    # - name: Create subscription
    #   run: |
    #     az extension add --name subscription \ 
    #     az account create --enrollment-account-name --offer-type {MS-AZR-0017P, MS-AZR-0148P}
    - name: Set variables
      run: |
        echo "TAG=$(date +%s)${{ github.run_attempt }}" >> $GITHUB_OUTPUT

    - name: Create blob container
      run: |
          az storage container create \
          -n test${{ env.TAG }} \
          --fail-on-exist \
          --account-name azureblobtescm \
        # --public-access {blob, container, off}
        # --blob-endpoint


