on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    # - name: Checkout code
    #   uses: actions/checkout@v2

    # - name: Set up QEMU
    #   uses: docker/setup-qemu-action@v2

    # - name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v2
    
    # - name: Set shared variables
    #   run: |
    #     echo "SHA_IMAGE_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    # - name: Check shared variables
    #   run: |
    #     echo ${{ env.SHA_IMAGE_TAG }}

      # - name: Build and push
      #   uses: docker/build-push-action@v4
      #   with:
      #     push: true
      #     tags: user/app:${{ env.SHA_IMAGE_TAG }}

    - name: Azure login
      uses: azure/login@v1
      with:
        client-id: "c1dc515b-43c4-4d19-9984-8771ba0e1873"
        tenant-id: "379f390a-2769-4d25-8acd-6ffb425accd7"
        subscription-id: "abf38db5-7b20-44b1-bd72-4d06fabaabe1"
        allow-no-subscriptions: true

    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az storage blob upload-batch --account-name azureblobtescm  --auth-mode key -d 'blob-test-cm' -s .


    # - name: Deploy to Blob Storage
    #   uses: Azure/blob-upload-action@v1
    #   with:
    #     storageAccountName: '<your-storage-account-name>'
    #     containerName: '<your-container-name>'
    #     sourcePath: '<your-source-path>'
    #     destinationPath: '<your-destination-path>'
